// Auto-generated by sync-routes. Add "// MOSAIC:OVERRIDE" above to keep your version.
export { default } from "@mosaic/core/app/admin/testimonials/page";
export * from "@mosaic/core/app/admin/testimonials/page";
