// Auto-generated by sync-routes. Add "// @override" above to customize.
export { default } from "@mosaic/core/app/admin/new-from-link/page";
export * from "@mosaic/core/app/admin/new-from-link/page";
