// Auto-generated by sync-routes. Add "// MOSAIC:OVERRIDE" above to keep your version.
export { default } from "@mosaic/core/app/collections/[slug]/page";
export * from "@mosaic/core/app/collections/[slug]/page";
