// Generate a project's src/app route tree as thin re-exports of @mosaic/core
// routes. Lets a project share core's pages/handlers while overriding any file:
// add `// @override` to a project file and it will be left untouched.
//
//   node ../../core/scripts/sync-routes.mjs <projectDir>
import fs from "node:fs";
import path from "node:path";

const SPECIAL = new Set([
  "page.tsx", "route.ts", "layout.tsx", "not-found.tsx",
  "loading.tsx", "error.tsx", "template.tsx", "default.tsx",
  "sitemap.ts", "robots.ts",
]);

const scriptDir = path.dirname(new URL(import.meta.url).pathname);
const coreApp = path.resolve(scriptDir, "../src/app");
const projectDir = path.resolve(process.argv[2] || ".");
const projectApp = path.join(projectDir, "src/app");

let written = 0, skipped = 0;

function walk(dir) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) { walk(p); continue; }
    if (!SPECIAL.has(e.name)) continue;
    // The project owns its own root layout — never generate app/layout.tsx.
    const rel = path.relative(coreApp, p);
    if (rel === "layout.tsx") continue;
    emit(rel, e.name);
  }
}

function emit(rel, name) {
  const target = path.join(projectApp, rel);
  if (fs.existsSync(target) && fs.readFileSync(target, "utf8").includes("MOSAIC:OVERRIDE")) {
    skipped++; return;
  }
  const importPath = "@mosaic/core/app/" + rel.replace(/\.(tsx|ts)$/, "").split(path.sep).join("/");
  const isRoute = name === "route.ts";
  const isMeta = name === "sitemap.ts" || name === "robots.ts";
  const body = isMeta
    ? `// Auto-generated by sync-routes. Add "// MOSAIC:OVERRIDE" above to keep your version.\nexport { default } from "${importPath}";\nexport const dynamic = "force-dynamic";\n`
    : isRoute
    ? `// Auto-generated by sync-routes. Add "// MOSAIC:OVERRIDE" above to keep your version.\nexport * from "${importPath}";\n`
    : `// Auto-generated by sync-routes. Add "// MOSAIC:OVERRIDE" above to keep your version.\nexport { default } from "${importPath}";\nexport * from "${importPath}";\n`;
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, body);
  written++;
}

walk(coreApp);
console.log(`[sync-routes] ${projectDir}: wrote ${written}, skipped ${skipped} override(s).`);

// --- also sync the Prisma schema (to project root) and base globals.css ---
function copyIfNotOverridden(srcAbs, destAbs) {
  if (fs.existsSync(destAbs) && fs.readFileSync(destAbs, "utf8").includes("MOSAIC:OVERRIDE")) return false;
  fs.mkdirSync(path.dirname(destAbs), { recursive: true });
  fs.copyFileSync(srcAbs, destAbs);
  return true;
}
const coreRoot = path.resolve(scriptDir, "..");
copyIfNotOverridden(path.join(coreRoot, "prisma/schema.prisma"), path.join(projectDir, "schema.prisma"));
copyIfNotOverridden(path.join(coreRoot, "src/styles/globals.css"), path.join(projectDir, "src/app/globals.css"));
console.log("[sync-routes] schema.prisma + globals.css synced.");
